name: 'northwind'
version: '1.0.0'
profile: 'northwind'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  northwind:
    +delimiter: ";"

models:
  northwind:
    staging:
      +materialized: view      # leve, sem joins — view está ótimo
    intermediate:
      +materialized: table     # joins pesados — melhor materializar
    marts:
      +materialized: table     # consumo final — precisa ser rápido
